name: booster_app
description: Booster - 팀 기반 습관 챌린지 앱 (목업 → Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  geolocator: ^14.0.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/booster_emblem.png
